apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-feature-download
  labels:
    env  : binance
    app  : main_features
    owner: DenisTashirev
    task : read_tick_from_binance
    run_from: deployment-feature-download.yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      project: binance
  template:
    metadata:
      labels:
        project: binance
    spec:
      containers:
        - name : feature-download
          image: feature_download:v2
