apiVersion: v1
kind: Pod
metadata:
  name: feature-download
  labels:
    env  : binance
    app  : main_features
    owner: DenisTashirev
    task : read_tick_from_binance
    run_from: pod-feature-download.yaml
spec:
  containers:
    - name : feature-download
      image: feature_download:v1